# Generated by Django 3.2.dev20200730101900 on 2021-05-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210519_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default='0000-00-00'),
        ),
    ]
