# Generated by Django 3.2.dev20200730101900 on 2021-05-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default='2001-01-01'),
        ),
    ]
